# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33f69edf56d76e3cf5f79a309bd462816ff897a198982d87f4af59ddd2b7759b5fbbfc3b86de306793d400d0e5432ad5f172114150d5af07744d0ce81f4c9fd1

test:
  secret_key_base: 2f1ebf0486f00409721eb0c378fc2a6cf51af904a6e6381c9c01277949e482b9b97ff8362610132a928bcebffc4b13905b570e01850576eb3afb4a676b8a85eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 3b0f195dd9c6f4426292b1e5b64a37759bc2c9a8499fc32891b6f6ebe30ef4f84f3709d01a54333edf34273c90bf72961ddc7742b71712297b49f07bd62723ad
